# Generated by Django 3.2 on 2021-04-30 07:16

from django.db import migrations


def add_init_data(apps, schema_editor):
    RollingStockType = apps.get_model("app", "RollingStockType")
    RollingStock = apps.get_model("app", "RollingStock")

    type1 = RollingStockType.objects.create(
        min_weight=1, max_weight=10, max_count=10, product_types="r"
    )
    type2 = RollingStockType.objects.create(
        min_weight=5, max_weight=8, max_count=6, product_types="rs"
    )

    RollingStock.objects.create(rolling_stock_type=type1, max_capacity=72)
    RollingStock.objects.create(rolling_stock_type=type1, max_capacity=90)
    RollingStock.objects.create(rolling_stock_type=type2, max_capacity=60)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_init_data),
    ]
